on:
  push:
    branches:
    - v2q
name: V2
env:
  RACK_SDK_VERSION: 2.git.588342d7
  RACK_DIR: ${GITHUB_WORKSPACE}/Rack-SDK
  RACK_USER_DIR: ${GITHUB_WORKSPACE}
jobs:
  buildLinux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Linux
      uses: ./.github/actions/build_linux
    - name: upload zip
      run: sh ./.github/actions/upload_plugin_lin/script.sh ${{ secrets.GITHUB_TOKEN }}
