on:
  push:
    branches:
    - develop
name: Develop
env:
  RACK_SDK_VERSION: 2.0.5
jobs:
  buildLinux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089
    - name: Build Linux
      uses: ./.github/actions/build_linux
