on:
  push:
    branches:
    - v2
name: V2
env:
  RACK_SDK_VERSION: 2.git.219bbaf1-win
jobs:
  buildWin:
    name: Build Windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Windows
      uses: ./.github/actions/build_win
