on:
  push:
    branches:
    - master
name: Build Master
env:
  PLUGIN_BUILD_VERSION: 1.1.0
jobs:
  buildLinux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Linux
      uses: ./.github/actions/build_linux
      env:
        RACK_SDK_VERSION: 1.1.6
    - name: Save artifact
      uses: actions/upload-artifact@v1
      with: 
        name: SubmarineFree-${{ env['PLUGIN_BUILD_VERSION'] }}-lin.zip
        path: ./dist/SubmarineFree-${{ env['PLUGIN_BUILD_VERSION'] }}-lin.zip
    ##- name: Upload Linux Release
    ##  uses: ./.github/actions/update_asset
    ##  env:
    ##    ASSET_PATH: dist/SubmarineFree-1.1.1-lin.zip
    ##    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    ##    RELEASE_TAG: latest
  buildWindows:
    name: Build Windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Windows
      uses: ./.github/actions/build_win
      env:
        RACK_SDK_VERSION: 1.1.6
    - name: Save artifact
      uses: actions/upload-artifact@v1
      with: 
        name: SubmarineFree-${{ env['PLUGIN_BUILD_VERSION'] }}-win.zip
        path: ./dist/SubmarineFree-${{ env['PLUGIN_BUILD_VERSION'] }}-win.zip
    ##- name: Upload Windows Release
    ##  uses: ./.github/actions/update_asset
    ##  env:
    ##    ASSET_PATH: dist/SubmarineFree-1.1.1-win.zip
    ##    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    ##    RELEASE_TAG: latest
  combineDist:
    name: Combine Distributions
    runs-on: ubuntu-latest
    needs: [buildLinux, buildWindows]
    steps:
    #- uses: actions/checkout@master
    - name: Download Linux
      uses: actions/download-artifact@v1
      with:
        name: SubmarineFree-${{ env['PLUGIN_BUILD_VERSION'] }}-lin.zip
        path: ./dist 
    - name: Download Windows
      uses: actions/download-artifact@v1
      with:
        name: SubmarineFree-${{ env['PLUGIN_BUILD_VERSION'] }}-win.zip
        path: ./dist 
    - name: Unzip
      run: unzip dist/*.zip -d ./dist
    - name: Remove Zipfiles
      run: rm dist/*.zip
    - name: Combine
      run: zip -q -9 -r SubmarineFree-${{ env['PLUGIN_BUILD_VERSION'] }}.zip ./dist/SubmarineFree
    - name: Save artifact 
      uses: actions/upload-artifact@v1
      with:
        name: SubmarineFree-${{ env['PLUGIN_BUILD_VERSION'] }}.zip
        path: ./SubmarineFree-${{ env['PLUGIN_BUILD_VERSION'] }}.zip
# TODO: This doesn't work :(
#  buildOsx:
#    name: Build OSX
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@master
#    - name: Build OSX
#      uses: ./.github/actions/build_osx
#      env:
#        RACK_SDK_VERSION: 1.1.4
#    - name: Tag Head as Latest
#      uses: ./.github/actions/update_tag
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        REF: refs/heads/master
#        TAG: latest
#    - name: Upload OSX Release
#      uses: ./.github/actions/update_asset
#      env:
#        ASSET_PATH: dist/vitamin-1.0.0-osx.zip
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        RELEASE_TAG: latest
