on:
  push:
    branches:
    - master
name: Build Master
env:
  PLUGIN_BUILD_VERSION: 1.1.0
jobs:
  buildLinux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Linux
      uses: ./.github/actions/build_linux
      env:
        RACK_SDK_VERSION: 1.1.6
    - name: Save artifact
      uses: actions/upload-artifact@v1
      with: 
        name: SubmarineFree-${{ env['PLUGIN_BUILD_VERSION'] }}-lin.zip
        path: ./dist/SubmarineFree-${{ env['PLUGIN_BUILD_VERSION'] }}-lin.zip
  buildWindows:
    name: Build Windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Windows
      uses: ./.github/actions/build_win
      env:
        RACK_SDK_VERSION: 1.1.6
    - name: Save artifact
      uses: actions/upload-artifact@v1
      with: 
        name: SubmarineFree-${{ env['PLUGIN_BUILD_VERSION'] }}-win.zip
        path: ./dist/SubmarineFree-${{ env['PLUGIN_BUILD_VERSION'] }}-win.zip
  buildOsx:
    name: Build OSX
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build OSX
      uses: ./.github/actions/build_osx
      env:
        RACK_SDK_VERSION: 1.1.6
    - name: Save artifact
      uses: actions/upload-artifact@v1
      with: 
        name: SubmarineFree-${{ env['PLUGIN_BUILD_VERSION'] }}-mac.zip
        path: ./dist/SubmarineFree-${{ env['PLUGIN_BUILD_VERSION'] }}-mac.zip
  combineDist:
    name: Combine Distributions
    runs-on: ubuntu-latest
    needs: [buildLinux, buildWindows, buildOsx]
    steps:
    - name: Download Linux
      uses: actions/download-artifact@v1
      with:
        name: SubmarineFree-${{ env['PLUGIN_BUILD_VERSION'] }}-lin.zip
        path: ./dist 
    - name: Download Windows
      uses: actions/download-artifact@v1
      with:
        name: SubmarineFree-${{ env['PLUGIN_BUILD_VERSION'] }}-win.zip
        path: ./dist 
    - name: Download Osx
      uses: actions/download-artifact@v1
      with:
        name: SubmarineFree-${{ env['PLUGIN_BUILD_VERSION'] }}-mac.zip
        path: ./dist 
    - name: Unzip
      run: unzip -o "dist/*.zip" -d ./dist
    - name: Remove Zipfiles
      run: rm dist/*.zip
    - name: Combine
      run: cd dist && zip -q -9 -r SubmarineFree-${{ env['PLUGIN_BUILD_VERSION'] }}.zip ./SubmarineFree
    - name: Save artifact 
      uses: actions/upload-artifact@v1
      with:
        name: SubmarineFree-${{ env['PLUGIN_BUILD_VERSION'] }}.zip
        path: ./dist/SubmarineFree-${{ env['PLUGIN_BUILD_VERSION'] }}.zip
